version: '3.4'

services:
  githubapi:
    container_name: githubapi
    image: ${DOCKER_REGISTRY-}githubapi
    environment:
        - PORT=5000
    ports:
        - 5000:5000 
    build:
      context: .
      dockerfile: Dockerfile
